# -*- coding: utf-8 -*-
"""stage 0_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pe6hkv6FZdThx7v65hnAnV_5WYCi3bWV

#Topics: Coding Syntax, Data types and Data Structure

##Task: Use any data structure of your choice to organize the following information

Your names, Your slack username, Your email, Your hobby, Your countries, Your discipline, Your preferred programming language
"""

# Storing the required information in a dictionary

team_info= [
    {
        "Name": "Kazadi Ngoie",
        "Slack Username": "@Tatiene",
        "Email": "tatianangoie17@gmail.com",
        "Hobby": "Gaming",
        "Country": "South Africa",
        "Discipline": "Bioinformatics",
        "Preferred Language": "Python"
    },
    {
        "Name": "Bezaleel Akinbami",
        "Slack Username": "@Bez",
        "Email": "bezaleelakinbami16@gmail.com",
        "Hobby": "Gaming",
        "Country": "Nigeria",
        "Discipline": "Bioinformatics ",
        "Preferred Language": "R"
    },
    {
        "Name": "Hana Nadir",
        "Slack Username": "@Hana",
        "Email": "hananadir04@gmail.com",
        "Hobby": "Reading",
        "Country": "Sudan",
        "Discipline": "Medecinal chemistery and drug discovery",
        "Preferred Language": "Python"
    },
    {
        "Name": "Onyinye Maryrose Ugwu ",
        "Slack Username": "@Onyinye",
        "Email": "monyinye80@gmail.com",
        "Hobby": "Travelling",
        "Country": "Nigeria",
        "Discipline": "Zoology",
        "Preferred Language": "Python"
    },
    {
        "Name": "Sanzida Akhter Anee",
        "Slack Username": "@Sanzida",
        "Email": "aneesanzidaakhter@gmail.com",
        "Hobby": "Blogging",
        "Country": "Bangladesh",
        "Discipline": "Bioinformatics",
        "Preferred Language": "Python"
    }
]

#to print all information in a structured way

print("Team Members Information:\n")

for member in team_info:
    print(f"Name: {member['Name']}")
    print(f"Slack Username: {member['Slack Username']}")
    print(f"Email: {member['Email']}")
    print(f"Hobby: {member['Hobby']}")
    print(f"Country: {member['Country']}")
    print(f"Discipline: {member['Discipline']}")
    print(f"Preferred Language: {member['Preferred Language']}")
    print("-" * 40)  # Separator for better readability